"""Generate BOARD.md or print repo-filtered ticket summaries.

Usage:
    python ixdar-tickets/generate_board.py board              # regenerate BOARD.md
    python ixdar-tickets/generate_board.py backlog REPO_NAME  # print tickets for a repo
"""

import argparse
import json
import re
import sys
from pathlib import Path


TICKETS_DIR = Path(__file__).parent / "content"
BOARD_PATH = Path(__file__).parent / "BOARD.md"
EPICS_PATH = TICKETS_DIR / "epics.json"

STATUS_ORDER = {"IN_PROGRESS": 0, "TODO": 1, "DONE": 2}
DESC_TRUNCATE = 100


def load_epics() -> tuple[dict[str, str], dict[str, int]]:
    """Return (prefix -> name, prefix -> priority) mappings."""
    if not EPICS_PATH.exists():
        return {}, {}
    with EPICS_PATH.open(encoding="utf-8") as f:
        data = json.load(f)
    names = {}
    priorities = {}
    for e in data.get("epics", []):
        names[e["prefix"]] = e["name"]
        priorities[e["prefix"]] = e.get("priority", 50)
    return names, priorities


def normalize_status(raw: str | None) -> str:
    if not raw:
        return "TODO"
    upper = raw.strip().upper()
    if upper in ("DONE", "COMPLETE", "COMPLETED"):
        return "DONE"
    if upper in ("IN_PROGRESS", "IN-PROGRESS", "WIP"):
        return "IN_PROGRESS"
    if upper in ("TODO", "OPEN", "BACKLOG"):
        return "TODO"
    return upper


def extract_prefix(ticket_id: str) -> str:
    match = re.match(r"^([A-Z]+)-", ticket_id)
    return match.group(1) if match else ""


def extract_number(ticket_id: str) -> int:
    match = re.search(r"-(\d+)$", ticket_id)
    return int(match.group(1)) if match else 0


def truncate(text: str, limit: int = DESC_TRUNCATE) -> str:
    if not text:
        return ""
    if len(text) <= limit:
        return text
    return text[:limit].rsplit(" ", 1)[0] + "..."


def load_tickets() -> list[dict]:
    tickets = []
    for category_dir in sorted(TICKETS_DIR.iterdir()):
        if not category_dir.is_dir():
            continue
        for ticket_file in sorted(category_dir.glob("*.json")):
            try:
                with ticket_file.open(encoding="utf-8") as f:
                    content = f.read().strip()
                    if not content.startswith("{"):
                        continue
                    data = json.loads(content)
            except (json.JSONDecodeError, OSError):
                continue
            ticket_id = data.get("id", ticket_file.stem)
            rel_path = ticket_file.relative_to(TICKETS_DIR.parent)
            tickets.append({
                "id": ticket_id,
                "title": data.get("title", ticket_id),
                "status": normalize_status(data.get("status")),
                "description": data.get("description", ""),
                "prefix": extract_prefix(ticket_id),
                "number": extract_number(ticket_id),
                "priority": data.get("priority", extract_number(ticket_id)),
                "rel_path": str(rel_path).replace("\\", "/"),
                "repo": data.get("repo", ""),
                "blocked_by": data.get("blocked-by", []),
                "blocks": data.get("blocks", []),
            })
    return tickets


def group_by_epic(
    tickets: list[dict],
) -> dict[str, dict[str, list[dict]]]:
    """Group tickets: epic prefix -> status -> sorted ticket list."""
    grouped: dict[str, dict[str, list[dict]]] = {}
    for t in tickets:
        prefix = t["prefix"]
        status = t["status"]
        grouped.setdefault(prefix, {}).setdefault(status, []).append(t)
    for epic_group in grouped.values():
        for ticket_list in epic_group.values():
            ticket_list.sort(key=lambda t: (t["priority"], t["number"]))
    return grouped


def render_ticket_line(t: dict, done: bool = False) -> str:
    if done:
        return (
            f"- ~~[{t['id']}]({t['rel_path']}) "
            f"**{t['id']}** {t['title']}~~"
        )
    desc = truncate(t["description"])
    desc_part = f" -- {desc}" if desc else ""
    return (
        f"- [{t['id']}]({t['rel_path']}) "
        f"**{t['id']}** {t['title']}{desc_part}"
    )


def render_board(
    grouped: dict[str, dict[str, list[dict]]],
    epic_names: dict[str, str],
    epic_priorities: dict[str, int],
) -> str:
    lines = [
        "# Ticket Board",
        "*Auto-generated by generate_board.py -- do not edit manually*",
        "",
    ]

    sorted_prefixes = sorted(
        grouped.keys(),
        key=lambda p: epic_priorities.get(p, 50),
    )

    for prefix in sorted_prefixes:
        status_groups = grouped[prefix]
        epic_name = epic_names.get(prefix, prefix)
        total = sum(len(v) for v in status_groups.values())
        epic_prio = epic_priorities.get(prefix, 50)
        lines.append(f"## {epic_name} ({total} tickets, priority {epic_prio})")
        lines.append("")

        # IN_PROGRESS
        in_progress = status_groups.get("IN_PROGRESS", [])
        if in_progress:
            lines.append(f"### In Progress ({len(in_progress)})")
            lines.append("")
            for t in in_progress:
                lines.append(render_ticket_line(t))
            lines.append("")

        # TODO
        todo = status_groups.get("TODO", [])
        if todo:
            lines.append(f"### Todo ({len(todo)})")
            lines.append("")
            for t in todo:
                lines.append(render_ticket_line(t))
            lines.append("")

        # DONE (collapsed)
        done = status_groups.get("DONE", [])
        if done:
            lines.append(f"<details><summary>Done ({len(done)})</summary>")
            lines.append("")
            for t in done:
                lines.append(render_ticket_line(t, done=True))
            lines.append("")
            lines.append("</details>")
            lines.append("")

        # Any non-standard statuses
        for status in sorted(status_groups.keys()):
            if status in STATUS_ORDER:
                continue
            other = status_groups[status]
            lines.append(f"### {status} ({len(other)})")
            lines.append("")
            for t in other:
                lines.append(render_ticket_line(t))
            lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)


def print_repo_tickets(repo: str) -> None:
    """Print a compact ticket summary filtered to a single repo.

    Groups by epic, shows actionable tickets (IN_PROGRESS, TODO) with
    priorities and dependency info, and a count of DONE tickets.
    """
    epic_names, epic_priorities = load_epics()
    all_tickets = load_tickets()
    repo_tickets = [t for t in all_tickets if t["repo"] == repo]

    if not repo_tickets:
        print(f"No tickets found for repo '{repo}'.")
        print(f"Available repos: {sorted({t['repo'] for t in all_tickets if t['repo']})}")
        return

    grouped = group_by_epic(repo_tickets)
    sorted_prefixes = sorted(
        grouped.keys(),
        key=lambda p: epic_priorities.get(p, 50),
    )

    for prefix in sorted_prefixes:
        status_groups = grouped[prefix]
        epic_name = epic_names.get(prefix, prefix)
        actionable = len(status_groups.get("IN_PROGRESS", [])) + len(status_groups.get("TODO", []))
        done_count = len(status_groups.get("DONE", []))
        print(f"\n{epic_name} ({prefix}) -- {actionable} actionable, {done_count} done")
        print("=" * 60)

        for status in ("IN_PROGRESS", "TODO"):
            tickets_in_status = status_groups.get(status, [])
            if not tickets_in_status:
                continue
            label = "IN PROGRESS" if status == "IN_PROGRESS" else "TODO"
            print(f"\n  {label}:")
            for t in tickets_in_status:
                deps = ""
                if t["blocked_by"]:
                    deps = f"  (blocked-by: {', '.join(t['blocked_by'])})"
                if t["blocks"]:
                    deps += f"  (blocks: {', '.join(t['blocks'])})"
                desc = truncate(t["description"], 80)
                print(f"    {t['id']} [P{t['priority']}] {t['title']}{deps}")
                if desc:
                    print(f"      {desc}")

        if done_count:
            print(f"\n  DONE: {done_count} tickets (use BOARD.md for details)")


def main() -> None:
    epic_names, epic_priorities = load_epics()
    tickets = load_tickets()
    grouped = group_by_epic(tickets)
    board = render_board(grouped, epic_names, epic_priorities)
    BOARD_PATH.write_text(board, encoding="utf-8")

    total_ip = sum(
        len(g.get("IN_PROGRESS", []))
        for g in grouped.values()
    )
    total_todo = sum(
        len(g.get("TODO", []))
        for g in grouped.values()
    )
    total_done = sum(
        len(g.get("DONE", []))
        for g in grouped.values()
    )
    print(
        f"Board updated: {total_ip} in-progress, "
        f"{total_todo} todo, {total_done} done"
    )


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="generate_board",
        description="Ticket board generator and backlog viewer.",
    )
    sub = parser.add_subparsers(dest="command")

    sub.add_parser("board", help="Regenerate BOARD.md from all ticket JSONs.")

    backlog_parser = sub.add_parser(
        "backlog",
        help="Print actionable tickets for a specific repo.",
    )
    backlog_parser.add_argument(
        "repo",
        help="Repository name to filter by (e.g. Blender-Procedural-Human).",
    )

    return parser


if __name__ == "__main__":
    parser = _build_parser()
    args = parser.parse_args()

    if args.command == "backlog":
        print_repo_tickets(args.repo)
    elif args.command == "board":
        main()
    else:
        parser.print_help()
        sys.exit(1)
