"""Generate BOARD.md or print repo-filtered ticket summaries.

Usage:
    python ixdar-tickets/generate_board.py board               # regenerate BOARD.md
    python ixdar-tickets/generate_board.py backlog REPO_NAME   # print tickets for a repo
    python ixdar-tickets/generate_board.py archive             # move DONE tickets to done/
    python ixdar-tickets/generate_board.py next-id EPIC        # print next ticket ID for epic
    python ixdar-tickets/generate_board.py mark done TICKET_ID # mark a ticket DONE and regenerate BOARD.md
"""

import argparse
import json
import re
import shutil
import sys
from pathlib import Path


ROOT_DIR = Path(__file__).parent
TICKETS_DIR = ROOT_DIR / "content"
DONE_DIR = ROOT_DIR / "done"
BOARD_PATH = ROOT_DIR / "BOARD.md"
EPICS_PATH = TICKETS_DIR / "epics.json"

STATUS_ORDER = {"IN_PROGRESS": 0, "TODO": 1, "DONE": 2}
DESC_TRUNCATE = 100


def load_epics() -> tuple[dict[str, str], dict[str, int]]:
    """Return (prefix -> name, prefix -> priority) mappings."""
    if not EPICS_PATH.exists():
        return {}, {}
    with EPICS_PATH.open(encoding="utf-8") as f:
        data = json.load(f)
    names = {}
    priorities = {}
    for e in data.get("epics", []):
        names[e["prefix"]] = e["name"]
        priorities[e["prefix"]] = e.get("priority", 50)
    return names, priorities


def normalize_status(raw: str | None) -> str:
    if not raw:
        return "TODO"
    upper = raw.strip().upper()
    if upper in ("DONE", "COMPLETE", "COMPLETED"):
        return "DONE"
    if upper in ("IN_PROGRESS", "IN-PROGRESS", "WIP"):
        return "IN_PROGRESS"
    if upper in ("TODO", "OPEN", "BACKLOG"):
        return "TODO"
    return upper


def extract_prefix(ticket_id: str) -> str:
    match = re.match(r"^([A-Z]+)-", ticket_id)
    return match.group(1) if match else ""


def extract_number(ticket_id: str) -> int:
    match = re.search(r"-(\d+)$", ticket_id)
    return int(match.group(1)) if match else 0


def truncate(text: str, limit: int = DESC_TRUNCATE) -> str:
    if not text:
        return ""
    if len(text) <= limit:
        return text
    return text[:limit].rsplit(" ", 1)[0] + "..."


def load_tickets() -> list[dict]:
    tickets = []
    for category_dir in sorted(TICKETS_DIR.iterdir()):
        if not category_dir.is_dir():
            continue
        for ticket_file in sorted(category_dir.glob("*.json")):
            try:
                with ticket_file.open(encoding="utf-8") as f:
                    content = f.read().strip()
                    if not content.startswith("{"):
                        continue
                    data = json.loads(content)
            except (json.JSONDecodeError, OSError):
                continue
            ticket_id = data.get("id", ticket_file.stem)
            rel_path = ticket_file.relative_to(TICKETS_DIR.parent)
            tickets.append({
                "id": ticket_id,
                "title": data.get("title", ticket_id),
                "status": normalize_status(data.get("status")),
                "description": data.get("description", ""),
                "prefix": extract_prefix(ticket_id),
                "number": extract_number(ticket_id),
                "priority": data.get("priority", extract_number(ticket_id)),
                "rel_path": str(rel_path).replace("\\", "/"),
                "repo": data.get("repo", ""),
                "blocked_by": data.get("blocked-by", []),
                "blocks": data.get("blocks", []),
            })
    return tickets


def group_by_epic(
    tickets: list[dict],
) -> dict[str, dict[str, list[dict]]]:
    """Group tickets: epic prefix -> status -> sorted ticket list."""
    grouped: dict[str, dict[str, list[dict]]] = {}
    for t in tickets:
        prefix = t["prefix"]
        status = t["status"]
        grouped.setdefault(prefix, {}).setdefault(status, []).append(t)
    for epic_group in grouped.values():
        for ticket_list in epic_group.values():
            ticket_list.sort(key=lambda t: (t["priority"], t["number"]))
    return grouped


def render_ticket_line(t: dict, done: bool = False) -> str:
    if done:
        return (
            f"- ~~[{t['id']}]({t['rel_path']}) "
            f"**{t['id']}** {t['title']}~~"
        )
    desc = truncate(t["description"])
    desc_part = f" -- {desc}" if desc else ""
    return (
        f"- [{t['id']}]({t['rel_path']}) "
        f"**{t['id']}** {t['title']}{desc_part}"
    )


def render_board(
    grouped: dict[str, dict[str, list[dict]]],
    epic_names: dict[str, str],
    epic_priorities: dict[str, int],
) -> str:
    lines = [
        "# Ticket Board",
        "*Auto-generated by generate_board.py -- do not edit manually*",
        "",
    ]

    sorted_prefixes = sorted(
        grouped.keys(),
        key=lambda p: epic_priorities.get(p, 50),
    )

    for prefix in sorted_prefixes:
        status_groups = grouped[prefix]
        epic_name = epic_names.get(prefix, prefix)
        total = sum(len(v) for v in status_groups.values())
        epic_prio = epic_priorities.get(prefix, 50)
        lines.append(f"## {epic_name} ({total} tickets, priority {epic_prio})")
        lines.append("")

        # IN_PROGRESS
        in_progress = status_groups.get("IN_PROGRESS", [])
        if in_progress:
            lines.append(f"### In Progress ({len(in_progress)})")
            lines.append("")
            for t in in_progress:
                lines.append(render_ticket_line(t))
            lines.append("")

        # TODO
        todo = status_groups.get("TODO", [])
        if todo:
            lines.append(f"### Todo ({len(todo)})")
            lines.append("")
            for t in todo:
                lines.append(render_ticket_line(t))
            lines.append("")

        # DONE (collapsed)
        done = status_groups.get("DONE", [])
        if done:
            lines.append(f"<details><summary>Done ({len(done)})</summary>")
            lines.append("")
            for t in done:
                lines.append(render_ticket_line(t, done=True))
            lines.append("")
            lines.append("</details>")
            lines.append("")

        # Any non-standard statuses
        for status in sorted(status_groups.keys()):
            if status in STATUS_ORDER:
                continue
            other = status_groups[status]
            lines.append(f"### {status} ({len(other)})")
            lines.append("")
            for t in other:
                lines.append(render_ticket_line(t))
            lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)


def print_repo_tickets(repo: str) -> None:
    """Print a compact ticket summary filtered to a single repo.

    Groups by epic, shows actionable tickets (IN_PROGRESS, TODO) with
    priorities and dependency info, and a count of DONE tickets.
    """
    epic_names, epic_priorities = load_epics()
    all_tickets = load_tickets()
    repo_tickets = [t for t in all_tickets if t["repo"] == repo]

    if not repo_tickets:
        print(f"No tickets found for repo '{repo}'.")
        print(f"Available repos: {sorted({t['repo'] for t in all_tickets if t['repo']})}")
        return

    grouped = group_by_epic(repo_tickets)
    sorted_prefixes = sorted(
        grouped.keys(),
        key=lambda p: epic_priorities.get(p, 50),
    )

    for prefix in sorted_prefixes:
        status_groups = grouped[prefix]
        epic_name = epic_names.get(prefix, prefix)
        actionable = len(status_groups.get("IN_PROGRESS", [])) + len(status_groups.get("TODO", []))
        done_count = len(status_groups.get("DONE", []))
        print(f"\n{epic_name} ({prefix}) -- {actionable} actionable, {done_count} done")
        print("=" * 60)

        for status in ("IN_PROGRESS", "TODO"):
            tickets_in_status = status_groups.get(status, [])
            if not tickets_in_status:
                continue
            label = "IN PROGRESS" if status == "IN_PROGRESS" else "TODO"
            print(f"\n  {label}:")
            for t in tickets_in_status:
                deps = ""
                if t["blocked_by"]:
                    deps = f"  (blocked-by: {', '.join(t['blocked_by'])})"
                if t["blocks"]:
                    deps += f"  (blocks: {', '.join(t['blocks'])})"
                desc = truncate(t["description"], 80)
                print(f"    {t['id']} [P{t['priority']}] {t['title']}{deps}")
                if desc:
                    print(f"      {desc}")

        if done_count:
            print(f"\n  DONE: {done_count} tickets (use BOARD.md for details)")


def _scan_ticket_files(*dirs: Path) -> list[Path]:
    """Glob all ticket JSONs across multiple directories."""
    files = []
    for d in dirs:
        if not d.exists():
            continue
        for epic_dir in sorted(d.iterdir()):
            if epic_dir.is_dir():
                files.extend(sorted(epic_dir.glob("*.json")))
    return files


def archive_done() -> None:
    """Move all DONE tickets from content/ to done/, preserving epic subdirectories."""
    moved = []
    for epic_dir in sorted(TICKETS_DIR.iterdir()):
        if not epic_dir.is_dir():
            continue
        for ticket_file in sorted(epic_dir.glob("*.json")):
            try:
                data = json.loads(ticket_file.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                continue
            if normalize_status(data.get("status")) != "DONE":
                continue

            dest_dir = DONE_DIR / epic_dir.name
            dest_dir.mkdir(parents=True, exist_ok=True)
            dest = dest_dir / ticket_file.name
            shutil.move(str(ticket_file), str(dest))
            moved.append(f"{epic_dir.name}/{ticket_file.name}")

    if moved:
        print(f"Archived {len(moved)} done ticket(s) to done/:")
        for name in moved:
            print(f"  {name}")
    else:
        print("No DONE tickets to archive.")


def print_next_id(epic: str) -> None:
    """Find the highest ticket number for an epic across content/ and done/, print the next one."""
    prefix = epic.upper()
    pattern = re.compile(rf"^{re.escape(prefix)}-(\d+)\.json$")

    max_num = 0
    for ticket_file in _scan_ticket_files(TICKETS_DIR, DONE_DIR):
        match = pattern.match(ticket_file.name)
        if match:
            max_num = max(max_num, int(match.group(1)))

    next_id = f"{prefix}-{max_num + 1}"
    print(next_id)


def _write_board() -> tuple[int, int, int]:
    epic_names, epic_priorities = load_epics()
    tickets = load_tickets()
    grouped = group_by_epic(tickets)
    board = render_board(grouped, epic_names, epic_priorities)
    BOARD_PATH.write_text(board, encoding="utf-8")

    total_ip = sum(
        len(g.get("IN_PROGRESS", []))
        for g in grouped.values()
    )
    total_todo = sum(
        len(g.get("TODO", []))
        for g in grouped.values()
    )
    total_done = sum(
        len(g.get("DONE", []))
        for g in grouped.values()
    )
    return total_ip, total_todo, total_done


def regenerate_board() -> None:
    total_ip, total_todo, total_done = _write_board()
    print(
        f"Board updated: {total_ip} in-progress, "
        f"{total_todo} todo, {total_done} done"
    )


def _ticket_path(ticket_id: str) -> Path:
    normalized_id = ticket_id.strip().upper()
    prefix = extract_prefix(normalized_id)
    number = extract_number(normalized_id)
    if not prefix or number <= 0:
        raise ValueError(f"Invalid ticket ID '{ticket_id}'. Expected format like IX-3.")

    ticket_path = TICKETS_DIR / prefix / f"{normalized_id}.json"
    if not ticket_path.exists():
        raise FileNotFoundError(f"Ticket not found: {normalized_id}")
    return ticket_path


def _normalize_done_todos(todos: list[str]) -> list[str]:
    normalized = []
    for todo in todos:
        text = str(todo).strip()
        if not text:
            continue
        if text.startswith("DONE : "):
            normalized.append(text)
            continue
        if text.startswith("DONE:"):
            normalized.append(f"DONE : {text[len('DONE:'):].strip()}")
            continue
        normalized.append(f"DONE : {text}")
    return normalized


def mark_ticket_done(ticket_id: str) -> None:
    """Mark a ticket DONE, normalize todo prefixes, and regenerate BOARD.md."""
    ticket_path = _ticket_path(ticket_id)
    data = json.loads(ticket_path.read_text(encoding="utf-8"))
    normalized_id = data.get("id", ticket_id.strip().upper())

    data["status"] = "DONE"
    if isinstance(data.get("todos"), list):
        data["todos"] = _normalize_done_todos(data["todos"])

    ticket_path.write_text(json.dumps(data, indent=4) + "\n", encoding="utf-8")
    total_ip, total_todo, total_done = _write_board()
    print(f"Marked {normalized_id} DONE")
    print(
        f"Board updated: {total_ip} in-progress, "
        f"{total_todo} todo, {total_done} done"
    )


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="generate_board",
        description="Ticket board generator and backlog viewer.",
    )
    sub = parser.add_subparsers(dest="command")

    sub.add_parser("board", help="Regenerate BOARD.md from all ticket JSONs.")

    backlog_parser = sub.add_parser(
        "backlog",
        help="Print actionable tickets for a specific repo.",
    )
    backlog_parser.add_argument(
        "repo",
        help="Repository name to filter by (e.g. Blender-Procedural-Human).",
    )

    sub.add_parser("archive", help="Move all DONE tickets from content/ to done/.")

    next_id_parser = sub.add_parser(
        "next-id",
        help="Print the next available ticket ID for an epic.",
    )
    next_id_parser.add_argument(
        "epic",
        help="Epic prefix (e.g. BLEN, ENG, TRADE).",
    )

    mark_parser = sub.add_parser(
        "mark",
        help="Update ticket lifecycle state.",
    )
    mark_sub = mark_parser.add_subparsers(dest="mark_command")

    mark_done_parser = mark_sub.add_parser(
        "done",
        help="Mark a ticket DONE and regenerate BOARD.md.",
    )
    mark_done_parser.add_argument(
        "ticket_id",
        help="Ticket ID to mark done (e.g. IX-3).",
    )

    return parser


if __name__ == "__main__":
    parser = _build_parser()
    args = parser.parse_args()

    if args.command == "backlog":
        print_repo_tickets(args.repo)
    elif args.command == "board":
        regenerate_board()
    elif args.command == "archive":
        archive_done()
    elif args.command == "next-id":
        print_next_id(args.epic)
    elif args.command == "mark" and args.mark_command == "done":
        mark_ticket_done(args.ticket_id)
    else:
        parser.print_help()
        sys.exit(1)
