"""Generate tickets/BOARD.md from all ticket JSON files.

Reads tickets/content/epics.json for epic names and priorities, globs all
ticket JSONs, and writes a markdown board grouped by epic (sorted by epic
priority), then by status within each epic, then by ticket priority.

Usage: python tickets/generate_board.py
"""

import json
import re
from pathlib import Path


TICKETS_DIR = Path(__file__).parent / "content"
BOARD_PATH = Path(__file__).parent / "BOARD.md"
EPICS_PATH = TICKETS_DIR / "epics.json"

STATUS_ORDER = {"IN_PROGRESS": 0, "TODO": 1, "DONE": 2}
DESC_TRUNCATE = 100


def load_epics() -> tuple[dict[str, str], dict[str, int]]:
    """Return (prefix -> name, prefix -> priority) mappings."""
    if not EPICS_PATH.exists():
        return {}, {}
    with EPICS_PATH.open(encoding="utf-8") as f:
        data = json.load(f)
    names = {}
    priorities = {}
    for e in data.get("epics", []):
        names[e["prefix"]] = e["name"]
        priorities[e["prefix"]] = e.get("priority", 50)
    return names, priorities


def normalize_status(raw: str | None) -> str:
    if not raw:
        return "TODO"
    upper = raw.strip().upper()
    if upper in ("DONE", "COMPLETE", "COMPLETED"):
        return "DONE"
    if upper in ("IN_PROGRESS", "IN-PROGRESS", "WIP"):
        return "IN_PROGRESS"
    if upper in ("TODO", "OPEN", "BACKLOG"):
        return "TODO"
    return upper


def extract_prefix(ticket_id: str) -> str:
    match = re.match(r"^([A-Z]+)-", ticket_id)
    return match.group(1) if match else ""


def extract_number(ticket_id: str) -> int:
    match = re.search(r"-(\d+)$", ticket_id)
    return int(match.group(1)) if match else 0


def truncate(text: str, limit: int = DESC_TRUNCATE) -> str:
    if not text:
        return ""
    if len(text) <= limit:
        return text
    return text[:limit].rsplit(" ", 1)[0] + "..."


def load_tickets() -> list[dict]:
    tickets = []
    for category_dir in sorted(TICKETS_DIR.iterdir()):
        if not category_dir.is_dir():
            continue
        for ticket_file in sorted(category_dir.glob("*.json")):
            try:
                with ticket_file.open(encoding="utf-8") as f:
                    content = f.read().strip()
                    if not content.startswith("{"):
                        continue
                    data = json.loads(content)
            except (json.JSONDecodeError, OSError):
                continue
            ticket_id = data.get("id", ticket_file.stem)
            rel_path = ticket_file.relative_to(TICKETS_DIR.parent)
            tickets.append({
                "id": ticket_id,
                "title": data.get("title", ticket_id),
                "status": normalize_status(data.get("status")),
                "description": data.get("description", ""),
                "prefix": extract_prefix(ticket_id),
                "number": extract_number(ticket_id),
                "priority": data.get("priority", extract_number(ticket_id)),
                "rel_path": str(rel_path).replace("\\", "/"),
            })
    return tickets


def group_by_epic(
    tickets: list[dict],
) -> dict[str, dict[str, list[dict]]]:
    """Group tickets: epic prefix -> status -> sorted ticket list."""
    grouped: dict[str, dict[str, list[dict]]] = {}
    for t in tickets:
        prefix = t["prefix"]
        status = t["status"]
        grouped.setdefault(prefix, {}).setdefault(status, []).append(t)
    for epic_group in grouped.values():
        for ticket_list in epic_group.values():
            ticket_list.sort(key=lambda t: (t["priority"], t["number"]))
    return grouped


def render_ticket_line(t: dict, done: bool = False) -> str:
    if done:
        return (
            f"- ~~[{t['id']}]({t['rel_path']}) "
            f"**{t['id']}** {t['title']}~~"
        )
    desc = truncate(t["description"])
    desc_part = f" -- {desc}" if desc else ""
    return (
        f"- [{t['id']}]({t['rel_path']}) "
        f"**{t['id']}** {t['title']}{desc_part}"
    )


def render_board(
    grouped: dict[str, dict[str, list[dict]]],
    epic_names: dict[str, str],
    epic_priorities: dict[str, int],
) -> str:
    lines = [
        "# Ticket Board",
        "*Auto-generated by generate_board.py -- do not edit manually*",
        "",
    ]

    sorted_prefixes = sorted(
        grouped.keys(),
        key=lambda p: epic_priorities.get(p, 50),
    )

    for prefix in sorted_prefixes:
        status_groups = grouped[prefix]
        epic_name = epic_names.get(prefix, prefix)
        total = sum(len(v) for v in status_groups.values())
        epic_prio = epic_priorities.get(prefix, 50)
        lines.append(f"## {epic_name} ({total} tickets, priority {epic_prio})")
        lines.append("")

        # IN_PROGRESS
        in_progress = status_groups.get("IN_PROGRESS", [])
        if in_progress:
            lines.append(f"### In Progress ({len(in_progress)})")
            lines.append("")
            for t in in_progress:
                lines.append(render_ticket_line(t))
            lines.append("")

        # TODO
        todo = status_groups.get("TODO", [])
        if todo:
            lines.append(f"### Todo ({len(todo)})")
            lines.append("")
            for t in todo:
                lines.append(render_ticket_line(t))
            lines.append("")

        # DONE (collapsed)
        done = status_groups.get("DONE", [])
        if done:
            lines.append(f"<details><summary>Done ({len(done)})</summary>")
            lines.append("")
            for t in done:
                lines.append(render_ticket_line(t, done=True))
            lines.append("")
            lines.append("</details>")
            lines.append("")

        # Any non-standard statuses
        for status in sorted(status_groups.keys()):
            if status in STATUS_ORDER:
                continue
            other = status_groups[status]
            lines.append(f"### {status} ({len(other)})")
            lines.append("")
            for t in other:
                lines.append(render_ticket_line(t))
            lines.append("")

        lines.append("---")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    epic_names, epic_priorities = load_epics()
    tickets = load_tickets()
    grouped = group_by_epic(tickets)
    board = render_board(grouped, epic_names, epic_priorities)
    BOARD_PATH.write_text(board, encoding="utf-8")

    total_ip = sum(
        len(g.get("IN_PROGRESS", []))
        for g in grouped.values()
    )
    total_todo = sum(
        len(g.get("TODO", []))
        for g in grouped.values()
    )
    total_done = sum(
        len(g.get("DONE", []))
        for g in grouped.values()
    )
    print(
        f"Board updated: {total_ip} in-progress, "
        f"{total_todo} todo, {total_done} done"
    )


if __name__ == "__main__":
    main()
